export const CURRENT_ORDERS_LOAD = "CURRENT_ORDERS_LOAD";
export const CURRENT_ORDERS_FETCH = "CURRENT_ORDERS_FETCH";
export const CURRENT_ORDERS_ERROR = "CURRENT_ORDERS_ERROR";

export const GET_SHOP_STATUS_LOAD = "GET_SHOP_STATUS_LOAD";
export const GET_SHOP_STATUS_FETCH = "GET_SHOP_STATUS_FETCH";
// export const GET_SHOP_STATUS_ERROR = "GET_SHOP_STATUS_ERROR";

// export const SHOP_STATUS_LOAD = "SHOP_STATUS_LOAD";
// export const SHOP_STATUS_FETCH = "SHOP_STATUS_FETCH";
// export const SHOP_STATUS_ERROR = "SHOP_STATUS_ERROR";

// export const DELIVERY_ALERT = "DELIVERY_ALERT";

// export const CANCLE_ALERT = "CANCLE_ALERT";

// export const SET_TOKEN = "SET_TOKEN";

// export const GET_TOKEN = "GET_TOKEN";
