export const DELIVERY_ERROR = "DELIVERY_ERROR";

export const ACCEPT_ORDER_LOAD = "ACCEPT_ORDER_LOAD";
export const ACCEPT_ORDER_FETCH = "ACCEPT_ORDER_FETCH";
export const ACCEPT_ORDER_ERROR = "ACCEPT_ORDER_ERROR";

export const CHANGE_ALIGNMENT = "CHANGE_ALIGNMENT";

export const SELECT_DATE = "SELECT_DATE";

export const MAPPER_DATA = "MAPPER_DATA";

export const RESET_BTN_STATE = "RESET_BTN_STATE";