export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
export const PRODUCTS_FETCH = "PRODUCTS_FETCH";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const SINGLE_PRODUCT_LOAD = "SINGLE_PRODUCT_LOAD";
export const SINGLE_PRODUCT_FETCH = "SINGLE_PRODUCT_FETCH";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";

export const UPDATE_PRICE_LOAD = "UPDATE_PRICE_LOAD";
export const UPDATE_PRICE_FETCH = "UPDATE_PRICE_FETCH";
export const UPDATE_PRICE_ERROR = "UPDATE_PRICE_ERROR";

export const UPDATE_MULTIPLE_PRICE_LOAD = "UPDATE_MULTIPLE_PRICE_LOAD";
export const UPDATE_MULTIPLE_PRICE_FETCH = "UPDATE_MULTIPLE_PRICE_FETCH";
export const UPDATE_MULTIPLE_PRICE_ERROR = "UPDATE_MULTIPLE_PRICE_ERROR";

export const INACTIVE_LOAD = "INACTIVE_LOAD";
export const INACTIVE_FETCH = "INACTIVE_FETCH";
export const INACTIVE_ERROR = "INACTIVE_ERROR";

export const UNIT_FETCH = "UNIT_FETCH";

export const ADD_PRODUCT_LOAD = "ADD_PRODUCT_LOAD";
export const ADD_PRODUCT_FETCH = "ADD_PRODUCT_FETCH";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const GET_INACTIVE_LOAD = "GET_INACTIVE_LOAD";
export const GET_INACTIVE_FETCH = "GET_INACTIVE_FETCH";
export const GET_INACTIVE_ERROR = "GET_INACTIVE_ERROR";

export const SHOP_TYPE_FETCH = "SHOP_TYPE_FETCH";
export const SHOP_TYPE_LOAD = "SHOP_TYPE_LOAD";
export const SHOP_TYPE_ERROR = "SHOP_STATUS_ERROR";

export const ACTIVATE_LOAD = "ACTIVATE_LOAD";
export const ACTIVATE_FETCH = "ACTIVATE_FETCH";
export const ACTIVATE_ERROR = "ACTIVATE_ERROR";

export const PRODUCT_DELETE_ALERT = "PRODUCT_DELETE_ALERT";

export const PRODUCT_ADD_ALERT = "PRODUCT_ADD_ALERT";

export const PRODUCT_ACTIVATE_ALERT = "PRODUCT_ACTIVATE_ALERT";

export const ADD_UNIT = "ADD_UNIT";

export const PRICE_UPDATE = "PRICE_UPDATE";

export const UPDATE_PRODUCT_IMAGE_LOAD = "UPDATE_PRODUCT_IMAGE_LOAD";
export const UPDATE_PRODUCT_IMAGE_FETCH = "UPDATE_PRODUCT_IMAGE_FETCH";
export const UPDATE_PRODUCT_IMAGE_ERROR = "UPDATE_PRODUCT_IMAGE_ERROR";

export const CATEGORY_LOAD = "CATEGORY_LOAD";
export const CATEGORY_FETCH = "CATEGORY_FETCH";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
