export const PROFILE_LOAD = "PROFILE_LOAD";
export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const UPDATE_PROFILE_REQUEST_LOAD = "UPDATE_PROFILE_REQUEST_LOAD";
export const UPDATE_PROFILE_REQUEST_FETCH = "UPDATE_PROFILE_REQUEST_FETCH";
export const UPDATE_PROFILE_REQUEST_ERROR = "UPDATE_PROFILE_REQUEST_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const UPDATE_SERVICERANGE_LOAD = "UPDATE_SERVICERANGE_LOAD";
export const UPDATE_SERVICERANGE_FETCH = "UPDATE_SERVICERANGE_FETCH";
export const UPDATE_SERVICERANGE_ERROR = "UPDATE_SERVICERANGE_ERROR";

export const UPDATE_MOV_LOAD = "UPDATE_MOV_LOAD";
export const UPDATE_MOV_FETCH = "UPDATE_MOV_FETCH";
export const UPDATE_MOV_ERROR = "UPDATE_MOV_ERROR";

export const UPDATE_PROFILE_IMAGE_LOAD = "UPDATE_PROFILE_IMAGE_LOAD";
export const UPDATE_PROFILE_IMAGE_FETCH = "UPDATE_PROFILE_IMAGE_FETCH";
export const UPDATE_PROFILE_IMAGE_ERROR = "UPDATE_PROFILE_IMAGE_ERROR";