export const GET_STOCK_LOAD = "GET_STOCK_LOAD";
export const GET_STOCK_FETCH = "GET_STOCK_FETCH";
export const GET_STOCK_ERROR = "GET_STOCK_ERROR";

export const SET_STOCK_LOAD = "SET_STOCK_LOAD";
export const SET_STOCK_FETCH = "SET_STOCK_FETCH";
export const SET_STOCK_ERROR = "SET_STOCK_ERROR";

export const TOGGLE_SSTOCK_LOAD = "TOGGLE_SSTOCK_LOAD";
export const TOGGLE_SSTOCK_FETCH = "TOGGLE_SSTOCK_FETCH";
export const TOGGLE_SSTOCK_ERROR = "TOGGLE_SSTOCK_ERROR";

export const TOGGLE_MSTOCK_LOAD = "TOGGLE_MSTOCK_LOAD";
export const TOGGLE_MSTOCK_FETCH = "TOGGLE_MSTOCK_FETCH";
export const TOGGLE_MSTOCK_ERROR = "TOGGLE_MSTOCK_ERROR";

export const TOGGLE_LSTOCK_LOAD = "TOGGLE_LSTOCK_LOAD";
export const TOGGLE_LSTOCK_FETCH = "TOGGLE_LSTOCK_FETCH";
export const TOGGLE_LSTOCK_ERROR = "TOGGLE_LSTOCK_ERROR";