export {default as AddProduct} from "./AddProduct"
export {default as AllProducts} from "./AllProducts"
export {default as DeletedProducts} from "./DeletedProducts"
export {default as Home} from "./Home"
export {default as Order} from "./Order"
export {default as Profile} from "./Profile"
export {default as SignIn} from "./SignIn"
export {default as SignUp} from "./SignUp"